# Generated by Django 4.2 on 2023-04-25 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_post_post_type_alter_skill_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='field',
            field=models.CharField(choices=[('Embedded Systems', 'Embedded Systems'), ('App Development', 'App Development'), ('Programming Language', 'Programming Language'), ('Graphic Design', 'Graphics Design'), ('Machine Learning', 'Machine Learning'), ('Databases', 'Databases'), ('Web Backend', 'Web Backend'), ('Web Frontend', 'Web Frontend')], max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='design_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='occupancies',
            field=models.ManyToManyField(blank=True, to='hub.occupancy'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
