# Generated by Django 4.2 on 2023-04-28 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='members_available',
            field=models.ManyToManyField(blank=True, related_name='meetings_available', to='hub.student'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to='hub.student'),
        ),
    ]
